In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('result.csv')

In [3]:
df

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name,sentiment,category
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates,positive,Одежда
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses,positive,Одежда
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses,negative,Одежда
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants,positive,одежда
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses,positive,Одежда
5,5,1080,49,Not for the very petite,"I love tracy reese dresses, but this one is no...",2,0,4,General,Dresses,Dresses,negative,Одеялье
6,6,858,39,Cagrcoal shimmer fun,I aded this in my basket at hte last mintue to...,5,1,1,General Petite,Tops,Knits,positive,одежда
7,7,858,39,"Shimmer, surprisingly goes with lots","I ordered this in carbon for store pick up, an...",4,1,4,General Petite,Tops,Knits,positive,одежда
8,8,1077,24,Flattering,I love this dress. i usually get an xs but it ...,5,1,0,General,Dresses,Dresses,positive,Одежда
9,9,1077,34,Such a fun dress!,"I'm 5""5' and 125 lbs. i ordered the s petite t...",5,1,0,General,Dresses,Dresses,positive,Одежда
10,10,1077,53,Dress looks like it's made of cheap material,Dress runs small esp where the zipper area run...,3,0,14,General,Dresses,Dresses,negative,Одежда
11,11,1095,39,NaN,This dress is perfection! so pretty and flatte...,5,1,2,General Petite,Dresses,Dresses,positive,одежда
12,12,1095,53,Perfect!!!,More and more i find myself reliant on the rev...,5,1,2,General Petite,Dresses,Dresses,positive,Одежда
13,13,767,44,Runs big,Bought the black xs to go under the larkspur m...,5,1,0,Initmates,Intimate,Intimates,neutral,Одежда
14,14,1077,50,Pretty party dress with some issues,This is a nice choice for holiday gatherings. ...,3,1,1,General,Dresses,Dresses,negative,Качество ткани
15,15,1065,47,"Nice, but not for my body",I took these out of the package and wanted the...,4,1,3,General,Bottoms,Pants,neutral,Одежда
16,16,1065,34,"You need to be at least average height, or taller",Material and color is nice. the leg opening i...,3,1,2,General,Bottoms,Pants,negative,Одежда
17,17,853,41,Looks great with white pants,Took a chance on this blouse and so glad i did...,5,1,0,General,Tops,Blouses,positive,Одежда
18,18,1120,32,Super cute and cozy,"A flattering, super cozy coat. will work well...",5,1,0,General,Jackets,Outerwear,positive,одежда
19,19,1077,47,Stylish and comfortable,I love the look and feel of this tulle dress. ...,5,1,0,General,Dresses,Dresses,positive,одежда
20,20,847,33,"Cute, crisp shirt","If this product was in petite, i would get the...",4,1,2,General,Tops,Blouses,positive,одежда
21,21,1080,55,I'm torn!,"I'm upset because for the price of the dress, ...",4,1,14,General,Dresses,Dresses,negative,Ценность и качество товара
22,22,1077,31,Not what it looks like,"First of all, this is not pullover styling. th...",2,0,7,General,Dresses,Dresses,negative,Недовольство по поводу дизайна и качества товара
23,23,1077,34,"Like it, but don't love it.",Cute little dress fits tts. it is a little hig...,3,1,0,General,Dresses,Dresses,neutral,Одежда
24,24,847,55,Versatile,"I love this shirt because when i first saw it,...",5,1,0,General,Tops,Blouses,positive,Одежда
25,25,697,31,Falls flat,"Loved the material, but i didnt really look at...",3,0,0,Initmates,Intimate,Lounge,negative,одежда
26,26,949,33,Huge disappointment,I have been waiting for this sweater coat to s...,2,0,0,General,Tops,Sweaters,negative,Одежда
27,27,1003,31,"Loved, but returned",The colors weren't what i expected either. the...,4,1,0,General,Bottoms,Skirts,negative,Одежда
28,28,684,53,Great shirt!!!,I have several of goodhyouman shirts and i get...,5,1,2,Initmates,Intimate,Lounge,positive,одежда
29,29,4,28,Great layering piece,This sweater is so comfy and classic - it bala...,5,1,0,General,Tops,Sweaters,positive,одежда
30,30,1060,33,NaN,Beautifully made pants and on trend with the f...,5,1,0,General Petite,Bottoms,Pants,positive,Одежда
31,31,1060,46,Cuter in oerson!,I never would have given these pants a second ...,5,1,7,General Petite,Bottoms,Pants,positive,Одежда
32,32,1060,21,Love these pants,These pants are even better in person. the onl...,5,1,0,General Petite,Bottoms,Pants,positive,Одежда
33,33,949,36,Mehh,"I ordered this 3 months ago, and it finally ca...",2,0,0,General,Tops,Sweaters,negative,Качество товара
34,34,697,39,Love this dress!,This is such a neat dress. the color is great ...,5,1,0,Initmates,Intimate,Lounge,positive,Одежда
35,35,1060,65,Lovely!,Wouldn't have given them a second look but tri...,4,1,3,General Petite,Bottoms,Pants,positive,одежда
36,36,1002,29,NaN,This is a comfortable skirt that can span seas...,4,1,5,General,Bottoms,Skirts,positive,одежда
37,37,949,38,Beautifully cut lightweight coat,"Just ordered this in a small for me (5'6"", 135...",5,1,1,General,Tops,Sweaters,positive,одежда
38,38,684,36,NaN,Super cute and comfy pull over. sizing is accu...,5,1,2,Initmates,Intimate,Lounge,positive,одежда
39,39,862,59,NaN,Great casual top with flare. looks cute with g...,5,1,0,General,Tops,Knits,positive,Одежда
40,40,862,47,NaN,Pretty and unique. great with jeans or i have ...,4,1,1,General,Tops,Knits,positive,Одежда
41,41,862,40,NaN,This is a beautiful top. it's unique and not s...,5,1,0,General,Tops,Knits,positive,Одежда
42,42,910,23,Soft & lovely,This poncho is so cute i love the plaid check ...,5,1,0,General,Tops,Fine gauge,positive,одежда
43,43,89,67,Some things you should know...,"First, this is thermal ,so naturally i didn't ...",4,1,1,Initmates,Intimate,Sleep,neutral,Одежда
44,44,862,48,Beautiful!,Tried this on today at my local retailer and h...,5,1,9,General,Tops,Knits,positive,Одежда
45,45,862,43,Love the two tone design,I bought this item from online... the fit on t...,4,1,0,General,Tops,Knits,neutral,Размер и соответствие
46,46,862,40,NaN,I love this top. i wear it all the time. the ...,5,1,0,General,Tops,Knits,positive,Одежда
47,47,823,52,NaN,"Very comfortable, material is good, cut out on...",5,1,0,General,Tops,Blouses,positive,Одежда
48,48,910,56,Love the color!,"This sweater is perfect for fall...it's roomy,...",5,1,0,General,Tops,Fine gauge,positive,Одежда
49,49,862,33,Love the embroidery!,Really cute top! the embroidery on the collar ...,5,1,0,General,Tops,Knits,positive,Одежда
50,50,862,46,Cute for fall,This is a cute top that can transition easily ...,4,1,1,General,Tops,Knits,neutral,Одежда
51,51,862,41,Love,I absolutely love this bib tee! it's probably ...,5,1,2,General,Tops,Knits,positive,одежда
52,52,1104,39,NaN,"Love the color and style, but material snags e...",3,1,3,General,Dresses,Dresses,neutral,материал
53,53,862,39,Flattering and comfortable,Very soft and comfortable. the shirt has an un...,5,1,34,General,Tops,Knits,positive,Одежда
54,54,862,66,Cute top,Nice top. armholes are a bit oversized but as ...,4,1,2,General,Tops,Knits,neutral,Одежда
55,55,862,61,Soft and cute as can be!,This is an adorable top that i find to be extr...,5,1,2,General,Tops,Knits,positive,Одежда
56,56,368,33,NaN,I am pregnant and i thought this would be a gr...,2,0,3,Initmates,Intimate,Intimates,negative,Одежда
57,57,862,31,"Boring front, great back",This tank fit well and i loved the ruffle in t...,3,0,0,General,Tops,Knits,negative,Одежда
58,58,1095,36,NaN,"I got this in the petite length, size o, and i...",4,1,0,General Petite,Dresses,Dresses,neutral,Одежда
59,59,368,52,Soft and comfortable,I've been looking for bralettes that provide s...,4,1,1,Initmates,Intimate,Intimates,neutral,Бельё

In [4]:
df = df[['Review Text', 'sentiment', 'category']]
df

,Review Text,sentiment,category
0,Absolutely wonderful - silky and sexy and comf...,positive,Одежда
1,Love this dress! it's sooo pretty. i happene...,positive,Одежда
2,I had such high hopes for this dress and reall...,negative,Одежда
3,"I love, love, love this jumpsuit. it's fun, fl...",positive,одежда
4,This shirt is very flattering to all due to th...,positive,Одежда
5,"I love tracy reese dresses, but this one is no...",negative,Одеялье
6,I aded this in my basket at hte last mintue to...,positive,одежда
7,"I ordered this in carbon for store pick up, an...",positive,одежда
8,I love this dress. i usually get an xs but it ...,positive,Одежда
9,"I'm 5""5' and 125 lbs. i ordered the s petite t...",positive,Одежда
10,Dress runs small esp where the zipper area run...,negative,Одежда
11,This dress is perfection! so pretty and flatte...,positive,одежда
12,More and more i find myself reliant on the rev...,positive,Одежда
13,Bought the black xs to go under the larkspur m...,neutral,Одежда
14,This is a nice choice for holiday gatherings. ...,negative,Качество ткани
15,I took these out of the package and wanted the...,neutral,Одежда
16,Material and color is nice. the leg opening i...,negative,Одежда
17,Took a chance on this blouse and so glad i did...,positive,Одежда
18,"A flattering, super cozy coat. will work well...",positive,одежда
19,I love the look and feel of this tulle dress. ...,positive,одежда
20,"If this product was in petite, i would get the...",positive,одежда
21,"I'm upset because for the price of the dress, ...",negative,Ценность и качество товара
22,"First of all, this is not pullover styling. th...",negative,Недовольство по поводу дизайна и качества товара
23,Cute little dress fits tts. it is a little hig...,neutral,Одежда
24,"I love this shirt because when i first saw it,...",positive,Одежда
25,"Loved the material, but i didnt really look at...",negative,одежда
26,I have been waiting for this sweater coat to s...,negative,Одежда
27,The colors weren't what i expected either. the...,negative,Одежда
28,I have several of goodhyouman shirts and i get...,positive,одежда
29,This sweater is so comfy and classic - it bala...,positive,одежда
30,Beautifully made pants and on trend with the f...,positive,Одежда
31,I never would have given these pants a second ...,positive,Одежда
32,These pants are even better in person. the onl...,positive,Одежда
33,"I ordered this 3 months ago, and it finally ca...",negative,Качество товара
34,This is such a neat dress. the color is great ...,positive,Одежда
35,Wouldn't have given them a second look but tri...,positive,одежда
36,This is a comfortable skirt that can span seas...,positive,одежда
37,"Just ordered this in a small for me (5'6"", 135...",positive,одежда
38,Super cute and comfy pull over. sizing is accu...,positive,одежда
39,Great casual top with flare. looks cute with g...,positive,Одежда
40,Pretty and unique. great with jeans or i have ...,positive,Одежда
41,This is a beautiful top. it's unique and not s...,positive,Одежда
42,This poncho is so cute i love the plaid check ...,positive,одежда
43,"First, this is thermal ,so naturally i didn't ...",neutral,Одежда
44,Tried this on today at my local retailer and h...,positive,Одежда
45,I bought this item from online... the fit on t...,neutral,Размер и соответствие
46,I love this top. i wear it all the time. the ...,positive,Одежда
47,"Very comfortable, material is good, cut out on...",positive,Одежда
48,"This sweater is perfect for fall...it's roomy,...",positive,Одежда
49,Really cute top! the embroidery on the collar ...,positive,Одежда
50,This is a cute top that can transition easily ...,neutral,Одежда
51,I absolutely love this bib tee! it's probably ...,positive,одежда
52,"Love the color and style, but material snags e...",neutral,материал
53,Very soft and comfortable. the shirt has an un...,positive,Одежда
54,Nice top. armholes are a bit oversized but as ...,neutral,Одежда
55,This is an adorable top that i find to be extr...,positive,Одежда
56,I am pregnant and i thought this would be a gr...,negative,Одежда
57,This tank fit well and i loved the ruffle in t...,negative,Одежда
58,"I got this in the petite length, size o, and i...",neutral,Одежда
59,I've been looking for bralettes that provide s...,neutral,Бельё